name: test.infrastructure.access.id
on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: /opt/actions/azure-login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Run az commands'
        run: |
          az account show
          az group list